import React, { useState } from 'react';
import { Database, ChevronDown, ChevronUp, AlertCircle, ShieldAlert, Info } from 'lucide-react';

export const DataSourcesAndLimitations: React.FC = () => {
  const [showLimitations, setShowLimitations] = useState(false);

  const sources = [
    { title: 'Candidate Profile', desc: 'Core identity, role target, experience timeline' },
    { title: 'Resume Information', desc: 'Stated skills, project summaries, education records' },
    { title: 'Interview Responses', desc: 'Technical answers, latency timings, conceptual explanations' },
    { title: 'Gemini AI Analysis', desc: 'Semantic reasoning, answer quality, inconsistency flags' },
    { title: 'Risk Engine', desc: 'Deterministic multi-signal scoring model (0-100 scale)' },
    { title: 'OpenCV Service', desc: 'Real-time face detection, eye cascades, attendee count' },
  ];

  return (
    <div className="space-y-4">
      {/* 13. Data Sources */}
      <div className="rounded-xl bg-slate-900/60 border border-slate-800/80 p-6 space-y-4">
        <div className="flex items-center gap-2.5 pb-3 border-b border-slate-800/80">
          <div className="w-7 h-7 rounded-lg bg-cyan-950/60 border border-cyan-800/60 flex items-center justify-center text-cyan-400">
            <Database className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white tracking-tight">Analysis Sources & Telemetry</h3>
            <p className="text-[11px] text-slate-400">Auditable inputs feeding this explainable verification report</p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {sources.map((s, idx) => (
            <div key={idx} className="p-3 rounded-lg bg-slate-950/60 border border-slate-800 space-y-1">
              <span className="text-[11px] font-semibold text-slate-200 block truncate">{s.title}</span>
              <p className="text-[10px] text-slate-400 leading-tight">{s.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* 14. Expandable Analysis Limitations */}
      <div className="rounded-xl bg-slate-900/60 border border-slate-800/80 overflow-hidden">
        <button
          onClick={() => setShowLimitations(!showLimitations)}
          className="w-full p-4 flex items-center justify-between text-left hover:bg-slate-800/30 transition-colors"
        >
          <div className="flex items-center gap-2 text-xs font-semibold text-slate-300">
            <AlertCircle className="w-4 h-4 text-cyan-400" />
            <span>Analysis Limitations & Regulatory Scope</span>
          </div>
          <div className="text-slate-400">
            {showLimitations ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </div>
        </button>

        {showLimitations && (
          <div className="px-5 pb-5 pt-1 space-y-3 text-xs text-slate-400 border-t border-slate-800/60 leading-relaxed">
            <p>
              • <strong className="text-slate-300">Algorithmic Confidence Bounds:</strong> AI evaluations, semantic relevance ratings, and response scores are generated by probabilistic machine learning models and must not be treated as empirical proof of candidate dishonesty or external assistance.
            </p>
            <p>
              • <strong className="text-slate-300">Sensory Constraints:</strong> Optical camera signals and Haar cascade classifiers can be influenced by ambient lighting, low-bandwidth video compression, eyeglasses glare, or multiple monitors.
            </p>
            <p>
              • <strong className="text-slate-300">Cognitive & Neurodiverse Variance:</strong> Natural speech pauses, gaze direction shifts, and response latencies vary widely across individuals and cultural backgrounds.
            </p>
          </div>
        )}
      </div>

      {/* 15. Final Human Review Notice */}
      <div className="p-4 rounded-xl bg-cyan-950/30 border border-cyan-800/40 flex items-start gap-3 text-xs">
        <div className="p-1 rounded bg-cyan-950/80 border border-cyan-700/50 text-cyan-400 shrink-0 mt-0.5">
          <Info className="w-4 h-4" />
        </div>
        <div className="space-y-1">
          <span className="font-semibold text-cyan-200">Decision-Support Mandate:</span>
          <p className="text-slate-300 text-[11px] leading-relaxed">
            DefenseAI is an advisory decision-support system. Risk indicators and AI analysis should not be treated as definitive evidence of misconduct and must not be used as the sole basis for employment decisions. All final hiring outcomes require independent human recruiter verification.
          </p>
        </div>
      </div>
    </div>
  );
};
