import { CandidateProfile } from '../types/candidate';

export const PRIMARY_CANDIDATE: CandidateProfile = {
  id: 'DEF-2026-001',
  name: 'Alex Morgan',
  role: 'Frontend Developer',
  experienceYears: '2.5 Years',
  location: 'Mumbai, India',
  interviewStatus: 'Completed',
  avatarInitials: 'AM',
  email: 'alex.morgan@example.com',
  resume: {
    skills: [
      'React',
      'JavaScript',
      'TypeScript',
      'HTML',
      'CSS',
      'Node.js',
      'SQL',
    ],
    experienceYears: '2.5 Years',
    education: 'B.E. Computer Engineering',
    projects: [
      'E-commerce Dashboard',
      'Weather Application',
      'Task Management System',
    ],
    fileName: 'Alex_Morgan_Resume_2026.pdf',
    fileSizeBytes: 245760, // ~240 KB
    uploadedAt: 'Today · 09:15 AM',
    analysisStatus: 'Not Started',
  },
  questions: [
    {
      id: 'q-1',
      questionNumber: 1,
      questionText: 'Explain the difference between React state and props.',
      answerText:
        'Props are used to pass data from one component to another, while state is used to manage data that can change inside a component.',
      category: 'Technical',
      responseTimeSeconds: 42,
      notes: 'Direct conceptual response with accurate component model terminology.',
    },
    {
      id: 'q-2',
      questionNumber: 2,
      questionText: 'How would you optimize a slow React application?',
      answerText:
        'I would analyze unnecessary renders, use memoization where appropriate, optimize API calls, lazy load components, and inspect performance using browser developer tools.',
      category: 'Technical',
      responseTimeSeconds: 58,
      notes: 'Included Profiler DevTools inspection and dynamic code-splitting tactics.',
    },
    {
      id: 'q-3',
      questionNumber: 3,
      questionText: 'Explain REST API and HTTP methods.',
      answerText:
        'REST APIs allow systems to communicate using HTTP. Common methods include GET, POST, PUT, PATCH and DELETE.',
      category: 'Technical',
      responseTimeSeconds: 36,
      notes: 'Succinct explanation covering standard CRUD idempotency mappings.',
    },
  ],
};

export const CANDIDATE_ROSTER: CandidateProfile[] = [
  PRIMARY_CANDIDATE,
  {
    id: 'DEF-2026-002',
    name: 'Sarah Williams',
    role: 'Data Analyst',
    experienceYears: '3.0 Years',
    location: 'Bengaluru, India',
    interviewStatus: 'Completed',
    avatarInitials: 'SW',
    email: 's.williams@example.com',
    resume: {
      skills: ['Python', 'SQL', 'Tableau', 'Pandas', 'PowerBI', 'PostgreSQL'],
      experienceYears: '3.0 Years',
      education: 'B.Tech Information Technology',
      projects: ['Churn Prediction Pipeline', 'Revenue Analytics Model'],
      fileName: 'Sarah_Williams_CV.pdf',
      fileSizeBytes: 312000,
      uploadedAt: 'Today · 08:30 AM',
      analysisStatus: 'Not Started',
    },
    questions: [
      {
        id: 'sw-q1',
        questionNumber: 1,
        questionText: 'Explain the difference between WHERE and HAVING in SQL.',
        answerText:
          'WHERE filters individual rows before aggregation occurs, while HAVING filters group aggregates generated by GROUP BY.',
        category: 'Technical',
        responseTimeSeconds: 31,
      },
      {
        id: 'sw-q2',
        questionNumber: 2,
        questionText: 'How do you handle missing values in a production dataset?',
        answerText:
          'I inspect the missingness mechanism (MCAR, MAR, MNAR) and apply appropriate imputation techniques or indicator flags.',
        category: 'Problem Solving',
        responseTimeSeconds: 49,
      },
    ],
  },
  {
    id: 'DEF-2026-003',
    name: 'Elena Rostova',
    role: 'Distributed Systems Engineer',
    experienceYears: '5.0 Years',
    location: 'Berlin, Germany',
    interviewStatus: 'Completed',
    avatarInitials: 'ER',
    email: 'elena.r@example.com',
    resume: {
      skills: ['Go', 'Rust', 'Kubernetes', 'gRPC', 'Kafka', 'Raft Consensus'],
      experienceYears: '5.0 Years',
      education: 'M.S. Computer Science',
      projects: ['Distributed WAL Engine', 'Multi-Raft Sharding Proxy'],
      fileName: 'Elena_Rostova_Resume.pdf',
      fileSizeBytes: 420000,
      uploadedAt: 'Yesterday · 01:20 PM',
      analysisStatus: 'Not Started',
    },
    questions: [
      {
        id: 'er-q1',
        questionNumber: 1,
        questionText: 'How does Raft handle split votes during leader election?',
        answerText:
          'Raft uses randomized election timeouts so candidates do not time out concurrently, ensuring one candidate wins majority quorum quickly.',
        category: 'Architecture',
        responseTimeSeconds: 52,
      },
    ],
  },
];
